### PR TITLE
Add a Makevars file to set `-fcommon`

### PR DESCRIPTION
**Pull request by eddelbuettel**

### CODE REVIEW

**Comment by fboehm** [comment]
Thank you!

**Comment by eddelbuettel** [comment]
You are very welcome. I could send you another one to silence a few of the compiler warnings if you want, but you should be back now given the compiler behaviour change (and, speaking of which, I can probably help you get the proper `extern` in there.  Let me know if that is of interest....

**Comment by fboehm** [comment]
Thanks, @eddelbuettel ! Yes, if it's not too much trouble, I'd really appreciate additional PRs to silence compiler warnings and add the `extern` statements. I'm trying to revive this package and am grateful for assistance!

**Comment by fboehm** [comment]
For future reference, here is the discussion on stackoverflow, which includes helpful links:

https://stackoverflow.com/questions/65873175/why-does-r-package-qtlbim-installation-fail-locally-but-succeed-in-a-docker-co/65874171#65874171

**Comment by eddelbuettel** [comment]
Will do.  In the meantime, it would be kind if you could accept the answer as it is apprently suitable :)

**Pull request merged**
